swagger: '2.0'
info:
  description: Test Case API
  version: 1.0.0
  title: Test Case API
  contact:
    email: prokopenko.co@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: 193.200.173.204/
basePath: 
paths: